# Predicting Insights into Audiobook Trends

## Phase 1: Data Preparation and Visualization

### Group Name: Group 90
### Group Members: 
Vinayak Mahawar s3937971 <br>
Vikas. s3967625

## Table of Contents

* Introduction
    * Data Source
    * Data Details
    * Dataset Features
    * Target Features
* Goal and Objectives
* Data Cleaning and Preprocessing
    * Data Cleaning Steps
* Data Exploration and Visualization
    * Univariate Visualization
    * Two-Variable Visualization
    * Three Variable Visualization
* Literature Review
    * Background
    * Method
    * Challenges
    * Summary
    * Unlocking Insights
* Summary and Conclusions
* References

## Introduction

### Data Source

The Audible Dataset used in this assignment is sourced from Kaggle. It contains the details about the audiobooks from 1998 till 2025.

Link: https://www.kaggle.com/datasets/snehangsude/audible-dataset


### Data Details

The Dataset is about the audiobooks on 'audible.in'. The Data inside contains the information about the audiobooks like the authors and the release dates and represents important details of the audiobooks from 1998 till 2025. The CSV file used contains the raw data derived directly from 'Audible.in'. The Dataset contains 8 features and 87,490 observations.

#### Dataset Retrieval

- We have downloaded the dataset as a CSV file and saved it to our machines local environment.
- We Load all the necessary modules to run the project and thereafter read and retrive the data from the CSV file.
- Moreover we Describe and display the info of the data to better understand the features of the dataset like their datatypes.

In [1]:
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns

In [2]:
data = pd.read_csv("Phase1_Group90.csv")

In [3]:
data.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

In [4]:
data.describe()

,name,author,narrator,time,releasedate,language,stars,price
count,87489,87489,87489,87489,87489,87489,87489,87489
unique,82767,48374,29717,2284,5058,36,665,1011
top,The Art of War,"Writtenby:矢島雅弘,石橋遊",Narratedby:anonymous,2 mins,16-05-18,English,Not rated yet,586.00
freq,20,874,1034,372,773,61884,72417,5533

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: object(8)
memory usage: 5.3+ MB

### Dataset Features

| Feature Name  | Data Type               | Units       | Description                                        |
|---------------|-------------------------|-------------|----------------------------------------------------|
| name          | Nominal Categorical     | NA          | Name of the audiobook                              |
| author        | Nominal Categorical     | NA          | Author of the audiobook                            |
| narrator      | Nominal Categorical     | NA          | Narrator of the audiobook                          |
| time          | Numeric                 | Hours:Minutes | Length of the audiobook                          |
| releasedate   | Date                    | NA          | Release date of the audiobook                      |
| language      | Nominal Categorical     | NA          | Language in which the audiobook is available       |
| stars         | Ordinal Categorical     | NA          | Star rating the audiobook has received             |
| price         | Numeric                 | Currency    | Price of the audiobook on Audible                  |

The above decriptions are in coordination with the kaggle data source.

### Target Features

For this project, we have taken price as the target feature. It represents the price of the audiobooks in indian rupees(INR). Therefore, the price of the audiobooks will be predicted based on the descriptive variables.

## Goal and Objectives

The rise in popularity of audiobooks in recent times is indicative of a change in consumer preferences towards accessible and engaging narrative. As smartphones and audio streaming services such as Audible become more commonplace, audiobooks provide a convenient substitute for printed books, accommodating hectic schedules and multitasking tendencies. Audible, which is well-known for its vast collection and excellent productions, has been a major contributor to this trend. Audiobooks are more appealing because of their user-friendly design and celebrity narrations, which make literature accessible for daily tasks like housework or exercises. This trend highlights how society's consumer habits are changing and how timeless narrative is in the current day.

Main objective for this project is to predict the prices of the audiobooks in future based on the available features and in doing so also find the features which helps in the accuracy of the predictions. 

Here in this phase we gain some insights into data with some statistics and data visualizations.

Firstly we preprocess the data, cleaning it, etc. Thereafter, performing data exploration and visualizations as appropriate.

## Data Cleaning and Preprocessing

In this section, we will be performing data cleaning and preprocessing steps in order to get on with this project.

### Data Cleaning Steps

- Check the missing values
- Remove unwanted prefixes 
- edit the data to make is easy to read and understand
- editing the datatypes of the features to suit them better.

###### Let's First look for the missing values if any below

In [6]:
data.isnull().sum()

name           0
author         0
narrator       0
time           0
releasedate    0
language       0
stars          0
price          0
dtype: int64

###### Now, checking the author and narrator features of the datset

In [7]:
data['author']

0        Writtenby:GeronimoStilton
1            Writtenby:RickRiordan
2             Writtenby:JeffKinney
3            Writtenby:RickRiordan
4            Writtenby:RickRiordan
                   ...
87484       Writtenby:ChrisStewart
87485      Writtenby:StephenO'Shea
87486          Writtenby:MarkTwain
87487     Writtenby:LaurenceSterne
87488      Writtenby:MarkKurlansky
Name: author, Length: 87489, dtype: object

In [8]:
data['narrator']

0            Narratedby:BillLobely
1         Narratedby:RobbieDaymond
2            Narratedby:DanRussell
3        Narratedby:SoneelaNankani
4        Narratedby:JesseBernstein
                   ...
87484      Narratedby:ChrisStewart
87485        Narratedby:RobertFass
87486         Narratedby:FloGibson
87487       Narratedby:AntonLesser
87488       Narratedby:FleetCooper
Name: narrator, Length: 87489, dtype: object

#### Author & Narrator column
###### To make these easy to read and understand, we are getting these features rid of their unnecesary prefixes and proving them spaces between the first and the last name.

In [9]:
# Remove the 'Writtenby:' prefix from the 'author' column.
data['author'] = data['author'].str.replace('Writtenby:', '', regex=False)
data['author'].head()

# Function to add spaces between names
def add_spaces(names):
    spaced_names = []
    for name in names:
        spaced_name = ''
        for i, char in enumerate(name):
            # Add space before uppercase letters
            if i > 0 and char.isupper() and name[i - 1] not in ["'", '"']:
                spaced_name += ' '
            spaced_name += char
        spaced_names.append(spaced_name)
    return spaced_names

data['author'] = add_spaces(data['author'])

In [10]:
#Removing the 'narrated by:' suffix from 'narrator' column...
data['narrator'] = data['narrator'].str.replace('Narratedby:', '', regex=False)
data['narrator'].head()
# Function to add spaces between narrator names
def add_spaces(names):
    spaced_names = []
    for name in names:
        spaced_name = ''
        for i, char in enumerate(name):
            # Add space before uppercase letters (excluding the first one and after a single quote)
            if i > 0 and char.isupper() and name[i - 1] not in ["'", '"']:
                spaced_name += ' '
            spaced_name += char
        spaced_names.append(spaced_name)
    return spaced_names

data['narrator'] = add_spaces(data['narrator'])

#### Time Column
###### The time feature in the dataset represents the duration of the audiobook in string format, here we will standardize  it to numerical value in minutes for easier analysis.

In [11]:
def convert_time_to_minutes(time_str):
    # Use regex to find numbers followed by 'hrs' or 'mins'
    hours = 0
    minutes = 0
    hours_match = re.search(r'(\d+)\s*hrs', time_str)
    minutes_match = re.search(r'(\d+)\s*mins', time_str)

    if hours_match:
        hours = int(hours_match.group(1))
    if minutes_match:
        minutes = int(minutes_match.group(1))

    return hours * 60 + minutes


data['time'] = data['time'].apply(convert_time_to_minutes)

data['time'].head()

0    140
1    788
2    123
3    676
4    600
Name: time, dtype: int64

#### Release Date 
###### Similar to the above, we also change the datatype of the releasedate feature to datetime format.

In [12]:
#Release Date: This is currently a string; converting it to a datetime format would be more appropriate for any time-based analysis.
data['releasedate'] = pd.to_datetime(data['releasedate'], format='%d-%m-%y', errors='coerce')
data['releasedate']

0       2008-08-04
1       2018-05-01
2       2020-11-06
3       2021-10-05
4       2010-01-13
           ...
87484   2017-03-09
87485   2017-02-21
87486   2016-12-30
87487   2011-02-23
87488   2017-03-07
Name: releasedate, Length: 87489, dtype: datetime64[ns]

#### Stars
###### This column has two features: 1. The Ratings  & 2. Number of Ratings
###### So, we have to split the column 
###### Now getting on to the stars feature, in order to standardize it and make it beneficial for analysis we convert it to numerical values.

In [ ]:
data['stars'].str.replace('Not rated yet','0')
data['Total Ratings']=data['stars'].str.extract(r'(\d+)( *ratings*)')[0]
data['Total Ratings']=data['Total Ratings'].astype('Int64')
data['Total Ratings']=data['Total Ratings'].fillna(0)

data['stars']=data['stars'].str.extract(r'([0-9]\.*\d*)').astype('Float64')
data['stars']=data['stars'].fillna(0)

In [ ]:
data.head()

#### Price
###### Furthermore we also standardize the price feature by replacing and 'free' item price with numerical zero and converting datatype to float.

In [ ]:
# Replace 'Free' with '0' and remove any commas
data['price'] = data['price'].replace('Free', '0').str.replace(',', '')

# Convert the 'price' column to float
data['price'] = pd.to_numeric(data['price'], errors='coerce')

# You can then check the output with
data['price']

###### Moreover, to make the dataset look better we capitalize the first letter of the features and values of the language features, also renaming some of the column names.

In [ ]:
# Capitalize the first letter of each column name
data.columns = [column.capitalize() for column in data.columns]
data.rename(columns={
    'Stars': 'Stars(out of 5)',
    'Time': 'Time(in minutes)'
}, inplace=True)
data.head()

#### Language
###### Now, convert text to uniform case

In [ ]:
data.Language.unique()

In [ ]:
#capitalizeing the first letter
data['Language']=data['Language'].str.capitalize()
data.Language.unique()

In [ ]:
data.head()

###### Looking for some missing values

In [ ]:
data.isnull().sum()

In [ ]:
data.info()

## Data Exploration and Visualization

Our Dataset is now clean and ready to be explored and visualized.

### Univariate Visualization

#### Histogram of Time

We visualize the distribution of the duration of audiobooks using histogram. We can see from figure, most of the audiobooks have the duration within 1000 minutes.

In [ ]:
plt.figure(figsize=(10, 6), dpi = 60)
plt.hist(data['Time(in minutes)'], bins=30, color='skyblue', edgecolor='black')
plt.title('Distribution of Time (in minutes)')
plt.xlabel('Time (in minutes)')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

#### Histogram of Stars

We visualize the distribution of the star ratings of audiobooks using histogram. We can see from figure, most of the audiobooks have the star rating between zero to one.

In [ ]:
plt.figure(figsize=(10, 6), dpi = 60)
plt.hist(data['Stars(out of 5)'], bins=10, edgecolor='black')
plt.title('Distribution of Stars (out of 5)')
plt.xlabel('Stars (out of 5)')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

#### Histogram of Price

We visualize the distribution of prices of audiobooks using histogram. We can see from figure, most of the audiobooks have the prices between 500 to 1000 INR.

In [ ]:
plt.figure(figsize=(10, 6), dpi = 60)
plt.hist(data['Price'], bins=30, color='salmon', edgecolor='black')
plt.title('Distribution of Price')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

### Two-Variable Visualisation

In [ ]:
# Set the aesthetic style of the plots
sns.set(style="whitegrid")

#### Box Plot for Total Ratings vs Price
We plot Price vs total rating, this will help us understand if more expensive audiobooks tend to recieve more ratings or not. We can see from this that mid range audiobooks have higer ratings.

In [ ]:
# Create price bins
data['Price Bins'] = pd.cut(data['Price'], bins=[0, 200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, max(data['Price'])])

# Create a box plot for Total Ratings vs. Price Bins
plt.figure(figsize=(14, 8), dpi=80)
sns.boxplot(data=data, x='Price Bins', y='Total ratings')
plt.title('Distribution of Total Ratings Across Different Price Ranges')
plt.xlabel('Price Bins')
plt.ylabel('Total Ratings')
plt.xticks(rotation=45)
plt.show()

#### Scatter Plot for Time vs Stars
We plot Time vs Stars, this will help us understand the relation between the duration and average rating of the audiobooks. We can see from this that mid range audiobooks have higer ratings.

In [ ]:
plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='Time(in minutes)', y='Stars(out of 5)')
plt.title('Time (in minutes) vs. Stars')
plt.xlabel('Time (in minutes)')
plt.ylabel('Stars (out of 5)')
plt.show()

#### Scatter Plot for Price vs Stars
We plot Price vs Stars, this will help us understand the relation between the price  and average rating of the audiobooks. There are no clear correlation between price and rating, with high and low ratings across all price ranges. There's a concentration of low-rated audiobooks at lower prices, suggesting either a trend of lower quality at lower prices or a higher volume of lower-rated audiobooks at lower prices.

In [ ]:
plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='Price', y='Stars(out of 5)')
plt.title('Price vs. Stars')
plt.xlabel('Price')
plt.ylabel('Stars (out of 5)')
plt.show()

### Three-Variable Visualisation

#### Scatter Plot between audiobook duration, star rating and total number of ratings
We plot audiobook duration, star rating and total number of rating as intesity of the colour, we can see from the figure that while lengthier audiobooks tend to be centred around average ratings, shorter ones show a wide range of ratings. The colour intensity of the overall scores, however, does not clearly correspond with audiobook quality, suggesting a sophisticated grading methodology.

In [ ]:
# Sample 10,000 entries from the dataset
sampled_data = data.sample(n=10000, random_state=1)

In [ ]:
plt.figure(figsize=(10, 6))
scatter = plt.scatter(sampled_data['Time(in minutes)'], sampled_data['Stars(out of 5)'],
                      c=sampled_data['Total ratings'], cmap='viridis', alpha=0.6)
plt.colorbar(scatter, label='Total Ratings')
plt.xlabel('Time in minutes')
plt.ylabel('Stars out of 5')
plt.title('Scatter Plot of Time vs. Stars Colored by Total Ratings')
plt.grid(True)
plt.show()

#### Buble Chart between audiobook duration, star rating and Prices.
We plot audiobook duration, star rating and prices depending on the buble size. Although we can see from the figure that there is no clear correlation. There are expensive audiobooks having high ratings as well as low and vice versa. Therefore, price doesn't seem to be a strong indicator of either duration or rating.

In [ ]:
plt.figure(figsize=(10, 6))
bubble = plt.scatter(sampled_data['Time(in minutes)'], sampled_data['Stars(out of 5)'],
                     s=sampled_data['Price'] / 10, alpha=0.6, edgecolors='w', linewidth=0.5)
plt.xlabel('Time in minutes')
plt.ylabel('Stars out of 5')
plt.title('Bubble Chart of Time vs. Stars with Bubble Size as Price')
plt.grid(True)
plt.show()

#### 3D Scatter Plot between audiobook duration, prices and total ratings.
We plot audiobook duration, prices and total ratings. Here there is lack of a clear relationship between price, length, and total ratings suggests that ratings aren't a reliable indicator of any of those two variables. However, longer audiobooks typically receive higher amount of ratings.

In [ ]:
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
scatter3d = ax.scatter(sampled_data['Time(in minutes)'], sampled_data['Price'], sampled_data['Total ratings'],
                       c=sampled_data['Total ratings'], cmap='coolwarm', alpha=0.6)
fig.colorbar(scatter3d, ax=ax, label='Total Ratings')
ax.set_xlabel('Time in minutes')
ax.set_ylabel('Price')
ax.set_zlabel('Total Ratings')
ax.set_title('3D Scatter Plot of Time, Price, and Total Ratings')
plt.show()

# Literature Review

#### Background

In this respect, a pretty lovely landscape analysis of the audiobook industry is presented by the very research conducted based on the "Audible Dataset" collected in the range of 1998-2025. The Kaggle dataset comprises 87,490 observations, where the number is derived from its eight independent features, forming the basis for unraveling the patterns and trends of businesses that feature audiobooks. The project mainly focuses on thoroughly cleaning the data and visualization, trying to set up the groundwork for further detailed analysis.

The present study, therefore, would try to delve into the nuances of data cleaning and apply advanced visualization techniques, which could shed light upon how audiobooks have shaped their evolution over the years and may result in providing valuable insights for the stakeholders related to the industry.

#### Method

This thus becomes the methodology embraced in this project—a series of necessary steps towards finding meaning and understanding from the Audible Dataset. The first step, therefore, starts at a rather cumbersome stage of cleaning the data, where inconsistencies and missing values are corrected in readiness for data quality for analysis.

Subsequently, data preprocessing comes in, carrying the normalization and transformation of features to the required format for visualization and analysis. This is then followed by the core of the analysis by the statistical Exploratory Data Analysis (EDA) and graphical tools that span from univariate to multivariate visualization approaches in search of revealing any underlying trends, patterns, and relationships concealed within data.

#### Challenges

Unquestionably, effective data management with this scale imposes a daunting challenge. With more than 87,000 observations, computational constraints and potential biases are gigantic, calling for careful and thorough handling during processing. Another challenge will be how to ensure the integrity of the data throughout the years, given that this dataset spans such a long period in years. Equally important would be to scrutinize the data strictly since it may have some information that is old and out of context. Added to this is a variety of relationships in the data that further increase the complexity of the challenge and ask for quite sophisticated visualization techniques and tools to represent valuable insights for decision-making.

#### Conclusion

In essence, the journey within the Audible dataset bore very optimistic fruits in propelling us to understand the patterns and trends of the market much deeper. The dataset was, therefore, poised for detailed exploratory analysis with meticulous data cleaning and preprocessing efforts. The visualization techniques used have helped lay essential findings concerning the distribution and interrelationships of features, thus giving a glimpse of the emerging contours in the landscape of audiobook consumption. These results already enable something much more than just consumption patterns; an analysis of customer behavior and market trends can be made, serving as a solid basis for later modeling efforts. As it evolves, using more and more granular prediction methods with advanced analytics can give strategic advice to stakeholders interested in the audiobook industry.

#### Unlocking Insights

With the conclusion of this formative phase, the study now prepares the ground for a much more nuanced investigation into the audiobook industry. Very thoroughly cleaned and pre-processed data, it prepares the project team for plunging deep into the fine-grained details of market dynamics and consumer behavior. The idea of tapping into the potential of advanced analytics, harnessing the power of advanced analytics is done with the aim of unlocking key insights that will inform strategic decision-making and drive innovation within the industry. From predictive modeling to sentiment analysis, the opportunities are endless, laying a blueprint for how to handle the shifting sands in audiobooks. Because as the stakeholders gear up for the next chapter, one thing is obvious: the journey to make sense of this mystery called the audiobook industry is only just beginning.

## Summary and Conclusions

The Audible dataset study provides insightful information on the development of the audiobook market from 1998 to 2025. Meaningful analysis was made possible by the initial data pretreatment, which guaranteed the dataset's cleanliness and consistency. A thorough grasp of their distributions and interrelationships was obtained through the investigation of important parameters including audiobook length, price, and star ratings. While bivariate visualisations such as scatter plots and box plots revealed interesting correlations between pairs of features, univariate visualisations such as histograms emphasised the distribution patterns of these elements alone.

One interesting discovery is that lengthier audiobooks typically receive higher ratings, which may indicate that listeners regard longer content to be more interesting or important. But the research also revealed that pricing does not always affect audiobook ratings, suggesting that other elements are important in determining audience happiness and engagement. This realisation emphasises how crucial elements like genre, author reputation, and content quality are in determining how well-liked audiobooks are.

Predictive modelling may use these insights in the future to predict price patterns for audiobooks and pinpoint the elements that have the most impact on their performance. Stakeholders in the audiobook sector may optimise content offers and improve listener experiences by knowing the complex interactions among duration, pricing, and ratings.

## References

1. www.kaggle.com. (n.d.). Audible Dataset. [online] Available at: https://www.kaggle.com/datasets/snehangsude/audible-dataset.
 
2. Holtz, Y. (n.d.). Bubble plot. [online] The Python Graph Gallery. Available at: https://python-graph-gallery.com/bubble-plot/#:~:text=A%20bubble%20plot%20is%20a [Accessed 19 Apr. 2024].

3. matplotlib.org. (n.d.). 3D scatterplot — Matplotlib 3.7.1 documentation. [online] Available at: https://matplotlib.org/stable/gallery/mplot3d/scatter3d.html.

4. GeeksforGeeks. (2018). Split a text column into two columns in Pandas DataFrame. [online] Available at: https://www.geeksforgeeks.org/split-a-text-column-into-two-columns-in-pandas-dataframe/ [Accessed 19 Apr. 2024].


1. Larson, L. C. (2015). E-Books and Audiobooks. The Reading Teacher, 69(2), 169–177. https://doi.org/10.1002/trtr.1371
2. Anwar, K., Siddiqui, J., & Saquib Sohail, S. (2019). Machine Learning Techniques for Book Recommendation: An Overview. SSRN Electronic Journal. https://doi.org/10.2139/ssrn.3356349
3. Snelling, M. (2021). The Audiobook Market and Its Adaptation to Cultural Changes. Publishing Research Quarterly, 37(4). https://doi.org/10.1007/s12109-021-09838-1
4. http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A1265673. (n.d.). DIVA. Retrieved April 21, 2024, from https://www.diva-portal.org/smash/record.jsf?pid=diva2%3A1265673&dswid=-4471
5. Snelling, M. (2021). The Audiobook Market and Its Adaptation to Cultural Changes. Publishing Research Quarterly, 37(4). https://doi.org/10.1007/s12109-021-09838-1
6. Ridzuan, F., & Wan Zainon, W. M. N. (2019). A Review on Data Cleansing Methods for Big Data. Procedia Computer Science, 161(1), 731–738. https://doi.org/10.1016/j.procs.2019.11.177
7. Pinheiro, P., Fernandes, P. O., & Teixeira, J. P. (2018). Audiobooks business model - technologic challenges, case study. International Business Information Management Association Conference, IBIMA, 5139–5154. https://bibliotecadigital.ipb.pt/handle/10198/21694
8. Salloum, S., Huang, J. Z., & He, Y. (2019). Exploring and cleaning big data with random sample data blocks. Journal of Big Data, 6(1). https://doi.org/10.1186/s40537-019-0205-4
9. Jiang, L., Liu, S.-X., & Chen, C. (2019). Recent research advances on interactive machine learning. Journal of Visualization, 22(2), 401–417. https://doi.org/10.1007/s12650-018-0531-1
10. Gustafsson, H. (2021). The Market for Audiobooks. Logos, 32(2), 7–9. https://doi.org/10.1163/18784712-03104012